### ISSUE TITLE
feature request - dataset create autofills created_timestamp

### ISSUE THREAD

**Issue by hschellman** [ivmfnal/metacat#13]
metacat dataset create hms:protodune-sp-physics-generic
{'namespace': 'hms', 'name': 'protodune-sp-physics-generic', 'frozen': False, 'monotonic': False, 'parents': [], 'children': [], 'metadata': {}, 'creator': 'schellma', 'created_timestamp': None, 'file_meta_requirements': None, 'description': ''}

**Comment by ivmfnal** [comment]
done
