### ISSUE TITLE
Feature request:  metacat dataset list has an option to list the files in the dataset.  Clearer documentation on -l and -c would be useful

### ISSUE THREAD

**Issue by hschellman** [ivmfnal/metacat#15]
I'm trying to see what is in a dataset.  Here is what I get

<schellma> metacat dataset list -l schellma:protodune-sp-physics-generic
creator          created             prnt/chld files      namespace/name
---------------- ------------------- --------- ---------- ----------------------------------------
schellma         2022-10-08 13:41:54    0/0               schellma:protodune-sp-physics-generic

seems to say there are not files in the dataset

<schellma> metacat dataset list -c schellma:protodune-sp-physics-generic
schellma:protodune-sp-physics-generic

ditto, seems to think it is empty

<schellma> metacat query "files from schellma:protodune-sp-physics-generic" | grep -c root
674918

Is this expected behavior?

**Comment by ivmfnal** [comment]
Yes it is expected. The `metacat dataset list` command lists datasets by pattern, not files in the dataset
