### ISSUE TITLE
command line interface for storing queries

### ISSUE THREAD

**Issue by hschellman** [ivmfnal/metacat#18]
Can we get a python and command line API for storing queries.

**Comment by hschellman** [comment]
An update on this one.   Here are suggested interfaces for the stored queries. 

The samweb format is

samweb create-dataset <name of set> <"dimensions">

presumably one can just make a 

metacat query store -q <"dimensions"> -n <namespace:name> 

One question is if this goes into a namespace and if so which? Might be the user namespace. 

# list query shortcuts in namespace
metacat query list namespace
 
# show me the info (including the query itself) 
metacat query show namespace:name

may need to have a query that says, show me all the queries with a given field in them in my namespace.

**Comment by ivmfnal** [comment]
Done.
See https://metacat.readthedocs.io/en/latest/ui.html#named-queries
You will need to upgrade the client to 3.31.0
