### ISSUE TITLE
Installation instructions need to tell user to set up their preferred python before install

### ISSUE THREAD

**Issue by hschellman** [ivmfnal/metacat#2]
Can a note be added to the installation instructions telling people to make certain their preferred python is the path before doing an install.  In particular, have the install fail immediately.   This may be dune specific but I think a lot of people are going to have issues with compatibility if they build incorrectly.

**Comment by ivmfnal** [comment]
I think that whether the user uses "setup.py" to install the product or "pip", in both cases it is necessary to have their Python set up. Otherwise neither one of the mechanisms would work. I think how exactly the user sets up their preferred Python is beyond the scope of MetaCat documentation.
