### ISSUE TITLE
need an equivalent for samweb list-files --summary which provides size of sample in files and bytes or MB

### ISSUE THREAD

**Issue by hschellman** [ivmfnal/metacat#23]
<schellma> samweb list-files --summary "run_number 5141"
File count:	1925
Total size:	7896055062598
Event count:	739997

**Comment by hschellman** [comment]
The summary option right now only gives the # of files, having the size is very useful with rogue users.

**Comment by ivmfnal** [comment]
Done. Please upgrade client to 3.26.1
