### ISSUE TITLE
parentage with filenames instead of id

### ISSUE THREAD

**Issue by hschellman** [ivmfnal/metacat#24]
currently one gets just a file id # when one asks for the parentage.  Can we get the filenames as an option, people generally are going to want to see the names, not id's they can't interpret easily.

Also note the fid # is stored as a string, probably should be an integer? 

metacat file show -l -p np04_reco_keepup:np04_raw_run005141_0002_dl6_reco_14501905_0_20190102T010101.root
{'checksums': {'adler32': '4a4752e2',
               'enstore': '3131593441',
               'md5': 'd2e5cb511d7a463f5488f1b56d8ce08b'},
 'children': [],
 'created_timestamp': 1546432187.40415,
 'creator': 'dunepro',
 'fid': '9068757',
 'name': 'np04_raw_run005141_0002_dl6_reco_14501905_0_20190102T010101.root',
 'namespace': 'np04_reco_keepup',
 'parents': ['6605764'],
 'retired': False,
 'retired_by': None,
 'retired_timestamp': None,
 'size': 13453725766,
 'updated_by': None,
 'updated_timestamp': None}

**Comment by ivmfnal** [comment]
Done. Please upgrade client to 3.27.0

**Comment by hschellman** [comment]
will do.. Thanks
