### ISSUE TITLE
Another thing - tags for datasets - probably something to go in user interface

### ISSUE THREAD

**Issue by hschellman** [ivmfnal/metacat#26]
for autogenerating websites it may be useful to have some defined tags for production datasets similar to those used to classify rucio datasets.

Joe user can find datasets by looking tags. 

tags:
core.file_type
core.data_tier
core.run_type
DUNE.campaign
core.application.version
core.application.name

the script that makes the dataset should know these things and be able to set them as metadata for the dataset. 

I think this is a script that goes in the metacat utilities area, not a base feature but very handy.

**Comment by dougbenjamin** [comment]
Will there be a cli client?  Will there be a web portal with pull down choices.
