### ISSUE TITLE
Observation.  runs[any] in (5141,5143) is much much faster than runs[any] in 5141:5143

### ISSUE THREAD

**Issue by hschellman** [ivmfnal/metacat#34]
This is just an observation.  When I run with the range format (there is no 5142 I think) things run in seconds instead of ~ 1 minute for the range specification.

**Comment by ivmfnal** [comment]
Yes, this is a known issue: https://metacat.readthedocs.io/en/latest/mql.html#ranges-and-sets

**Comment by hschellman** [comment]
Should datasets have create/update dates and creators just like files do?   I’ve gotten some nice dataset creation going but it would be good to find the person who did it and when.

Thanks, Heidi

On Aug 19, 2023, at 4:22 PM, Igor Mandrichenko ***@***.******@***.***>> wrote:


[This email originated from outside of OSU. Use caution with links and attachments.]


Yes, this is a known issue: https://metacat.readthedocs.io/en/latest/mql.html#ranges-and-sets

**Comment by ivmfnal** [comment]
I think the best is to have the user choose between using value ranges and direct enumeration, knowing that using ranges is not indexable

**Comment by hschellman** [comment]
Yes, And Elisabetta, for example, asked me why I did not use a, b, c  instead of a-c so generally users are happy with “,” delimited.


On Aug 27, 2023, at 2:21 AM, Igor Mandrichenko ***@***.******@***.***>> wrote:


[This email originated from outside of OSU. Use caution with links and attachments.]


I think the best is to have the user choose between using value ranges and direct enumeration, knowing that using ranges is not indexable
