### ISSUE TITLE
Request:  recognize strings so you don't need to use quotes

### ISSUE THREAD

**Issue by hschellman** [ivmfnal/metacat#4]
metacat query "files where creator='calcuttj' limit 3"

just be creator=calcuttj?    I think you need to do something like if first character != a number or a boolean, assume it's a string.

**Comment by ivmfnal** [comment]
so what if the user wants to represent a string "3" ?
or what if the string contains a space ?

The above examples show that while this suggestion marginally reduces the amount of typing to enter a query, it does not completely eliminate the need to use quotes and makes the lexical analysis harder and in fact does not improve readability of the query

**Comment by hschellman** [comment]
I would say if you want “3” you say “3”.

People are going to be moving over from sam and having to use 2 types of quotes for basic queries is going to cause some woe.

I will presume that samweb somehow knows the types for various values and makes an assumption.  Ie, if creator is a string, it assumes the = is a string.  THat might be a better way of handling this.

THat of course assumes that either the client or the server knows all of these types but I believe they are set when you declare a new value.


On Sep 26, 2022, at 7:48 AM, Igor Mandrichenko ***@***.******@***.***>> wrote:


[This email originated from outside of OSU. Use caution with links and attachments.]


so what if the user wants to represent a string "3" ?
or what if the string contains a space ?

The above examples show that while this suggestion marginally reduces the amount of typing to enter a query, it does not completely eliminate the need to use quotes and makes the lexical analysis harder and in fact does not improve readability of the query

**Comment by ivmfnal** [comment]
done
