### ISSUE TITLE
metacat options ordering

### ISSUE THREAD

**Issue by hschellman** [ivmfnal/metacat#7]
Can we get a parser for metacat command line that treats

metacat file show -j dc4-hd-protodune:dc4_hd_protodune_20220928T024437_61501650_898_reco.root 

and 

metacat file show  dc4-hd-protodune:dc4_hd_protodune_20220928T024437_61501650_898_reco.root -j

and possibly --json the same? 

I use optparse which seems to make this easier.

Thanks, Heidi

**Comment by ivmfnal** [comment]
Done for most of commands. The exception is "metacat query" because all the command tail after word "query" is concatenated into the query and "-" can be used in the query, so something like "metacat query files from dc4:dc4 -..." could theoretically be a valid query.

The client needs to be upgraded to v 3.15.3

**Comment by hschellman** [comment]
Agreed.

I think some pre-checking before queries go to the server and and error 
recovery afterwards are going to be needed before we let users loose on 
this.

Any chance of going to optparser or argparser for the arguments, I think 
it would give you a lot more control.  I could come up with a short 
argparser version.


On 10/4/22 1:52 PM, Igor Mandrichenko wrote:
>
> [This email originated from outside of OSU. Use caution with links and 
> attachments.]
>
> Done for most of commands. The exception is "metacat query" because 
> all the command tail after word "query" is concatenated into the query 
> and "-" can be used in the query, so something like "metacat query 
> files from dc4:dc4 -..." could theoretically be a valid query.
>
> The client needs to be upgraded to v 3.15.3
>
> —
> Reply to this email directly, view it on GitHub 
> <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fivmfnal%2Fmetacat%2Fissues%2F7%23issuecomment-1267565087&data=05%7C01%7Cheidi.schellman%40oregonstate.edu%7Cedfd0df0df834a63c17508daa64a642e%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C638005135681876824%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sszn3l7ZzDY%2F%2BGYz1TH5eHUH9cDvjY34GIxHYSFPQpw%3D&reserved=0>, 
> or unsubscribe 
> <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIA37DMMJVWDMCL767JDSQTWBSKJ3ANCNFSM6AAAAAAQYFRG7A&data=05%7C01%7Cheidi.schellman%40oregonstate.edu%7Cedfd0df0df834a63c17508daa64a642e%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C638005135681876824%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wUikp%2B%2FeFIhSzJXLyoHzDkANfNhTkSKftTX3N4imjh0%3D&reserved=0>.
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>
>
-- 
Prof. Heidi Schellman
Oregon State University
DUNE Computing Consortium Lead

**Comment by ivmfnal** [comment]
I use standard Python getopt module. I think it is sufficient

**Comment by hschellman** [comment]
Check out optparse.  It can make your life a lot easier

On Oct 4, 2022, at 14:35, Igor Mandrichenko ***@***.***> wrote:

﻿

[This email originated from outside of OSU. Use caution with links and attachments.]

I use standard Python getopt module. I think it is sufficient
