### ISSUE TITLE
document the runs syntax

### ISSUE THREAD

**Issue by hschellman** [ivmfnal/metacat#8]
I don't think the docs do the runs syntax.  They say things like run = 2 where core.runs[any]=2 works now. 

Also I don't actually know how to do more than one run ie core.runs[?]=??

**Comment by ivmfnal** [comment]
I am not sure what you mean by "docs do the runs syntax". Runs is a DUNE specific data and I do not think they belong in MetaCat documentation.

DUNE SAM to MetaCat conversion is documented here: https://docs.google.com/spreadsheets/d/1H3VxGbZt8e3ag-HoRs34Adqr2uGAdRXgzqJ7mMX_bZI/edit?usp=sharing

MQL support for lists and dictionaries is documented here: https://metacat.readthedocs.io/en/latest/mql.html#array-or-dictionary-elements-access
