### ISSUE TITLE
metacat file datasets command not recognized

### ISSUE THREAD

**Issue by hschellman** [ivmfnal/metacat#9]
<schellma> metacat file datasets
Unknown command metacat file datasets

Usage for metacat file:
metacat file 
    declare        [options] [[<file namespace>:]<filename>] [<dataset namespace>:]<dataset name>
    declare-many   [options] <file list JSON file> [<dataset namespace>:]<dataset name>
    declare-sample -- print sample input for declare-many command
    add            [options] <dataset namespace>:<dataset name>
    update         [options] (@<JSON file with metadata>|'<JSON expression>')
    name           [options] <file id>  - print namespace, name
    fid            <namespace>:<name>|<namespace> <name>  - print file id
    show           [options] (-i|--id <file id>|<namespace>:<name>)

    help

**Comment by ivmfnal** [comment]
done
